import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center bg-slate-500`}>
        <div className="max-w-[927px] w-full bg-white ">
          {/* <Navbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
